using System.Linq;
using System.Collections.Generic;

namespace Visual_Inventory_System.Services
{
    /// <summary>
    /// Converts a human-readable location name (e.g. "External Yard") into its
    /// machine code (e.g. "ETRD") using a single, consistent rule:
    ///
    ///   Take the 1st, 3rd, 5th, and LAST letters/digits of the cleaned name.
    ///   Skip any position that doesn't exist, and never include the same
    ///   position twice (so when the 5th letter IS the last letter, it counts once).
    ///
    /// Examples:
    ///   "RD Lab"           -> RLB   (5th letter is also the last, so it collapses)
    ///   "External Yard"    -> ETRD
    ///   "New Test Cells"   -> NWES
    ///   "Plant Test Cells" -> PATS
    ///   "Trailer Area"     -> TALA
    ///   "Ninja"            -> NNA
    ///
    /// This is the ONLY place codes are generated. The controller calls Encode()
    /// before anything is written to the database, so the DB and the map always
    /// read codes, while the UI works in friendly names.
    /// </summary>
    public static class LocationCodec
    {
        public static string Encode(string? humanName)
        {
            if (string.IsNullOrWhiteSpace(humanName)) return "";

            // Keep only letters and digits, uppercased.
            var clean = new string(humanName.Where(char.IsLetterOrDigit).ToArray())
                              .ToUpperInvariant();
            if (clean.Length == 0) return "";

            int n = clean.Length;

            // Canonical positions (1-indexed): first, third, fifth, last.
            // De-duplicate (last may equal fifth) and keep ascending order.
            var positions = new[] { 1, 3, 5, n }
                .Where(p => p >= 1 && p <= n)
                .Distinct()
                .OrderBy(p => p);

            return new string(positions.Select(p => clean[p - 1]).ToArray());
        }

        // ----------------------------------------------------------------------
        // DECODE (code -> friendly name), for DISPLAY only.
        // The full real-world location vocabulary. Because codes are generated by
        // Encode(), the reverse map is built by encoding each name once, so Decode
        // is always the exact inverse for known locations. Storage stays coded;
        // this just turns the barcode back into a label when we show it.
        // ----------------------------------------------------------------------
        // FALLBACK ONLY. Before Pass 7C this array WAS the vocabulary, and it had
        // drifted: 34 variant rows carried Sub codes (MZA3-MZA8) it never knew about,
        // so every breadcrumb rendered them as raw codes. The vocabulary now lives in
        // the Locations table and is pushed in via Refresh() at startup and after any
        // Settings edit. This list survives only so Decode() still does something
        // sensible if it is ever called before the first Refresh.
        private static readonly string[] SeedNames = new[]
        {
            // Parents
            "RD Lab", "External Yard", "New Test Cells", "Plant Test Cells",
            // Majors
            "Metrology Mezzanine", "2-6", "Connex Area", "Trailer Area",
            // Subs
            "Samurai", "Ninja", "Connex Box 6", "Trailer 1"
        };

        // Read-mostly lookup, swapped wholesale rather than mutated, so a reader
        // mid-Decode always sees one complete map and never a half-built one.
        private static volatile Dictionary<string, string> _reverseMap = BuildReverseMap(SeedNames);

        private static Dictionary<string, string> BuildReverseMap(IEnumerable<string> names)
        {
            var map = new Dictionary<string, string>();
            foreach (var name in names)
            {
                if (string.IsNullOrWhiteSpace(name)) continue;
                var code = Encode(name);
                if (!string.IsNullOrEmpty(code) && !map.ContainsKey(code))
                    map[code] = name.Trim();
            }
            return map;
        }

        /// <summary>
        /// Point Decode() at the current Locations table. Called once at startup
        /// (Program.cs) and again after any location is added, renamed or hidden
        /// (SettingsController), so the friendly names never go stale mid-session.
        ///
        /// Encode() is untouched by this: the 1st/3rd/5th/last rule is still the
        /// only thing that turns a name into a code, which is why codes are derived
        /// and never stored -- there is nothing here that can disagree with it.
        /// </summary>
        public static void Refresh(IEnumerable<string> names)
        {
            _reverseMap = BuildReverseMap(names ?? System.Array.Empty<string>());
        }

        /// <summary>
        /// Friendly name for a stored location code. Unknown codes, already-friendly
        /// values, "0" and blanks are returned unchanged, so this is always safe to
        /// call on display without worrying about what's actually stored.
        /// </summary>
        public static string Decode(string? code)
        {
            if (string.IsNullOrWhiteSpace(code)) return code ?? "";
            return _reverseMap.TryGetValue(code.Trim(), out var name) ? name : code;
        }

        public static IReadOnlyDictionary<string, string> DecodeMap => _reverseMap;
    }
}
